- name: Install NFS client
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Create mount point
  file:
    path: "{{ nfs_mount_path }}"
    state: directory

- name: Mount NFS share
  mount:
    path: "{{ nfs_mount_path }}"
    src: "{{ nfs_server }}:{{ nfs_share_path }}"
    fstype: nfs
    state: mounted
    opts: rw
