- name: Install NFS client
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Create mount point
  file:
    path: "{{ nfs_mount_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Mount NFS share
  mount:
    src: "{{ nfs_server }}:{{ nfs_share_path }}"
    path: "{{ nfs_mount_path }}"
    fstype: nfs
    opts: rw,sync
    state: mounted

- name: Ensure mount is persistent
  mount:
    src: "{{ nfs_server }}:{{ nfs_share_path }}"
    path: "{{ nfs_mount_path }}"
    fstype: nfs
    opts: rw,sync
    state: present
