- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: true

- name: Deploy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: true
