- name: Install NFS server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Create NFS export directory
  file:
    path: "{{ nfs_share_path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Add NFS export block to /etc/exports
  blockinfile:
    path: /etc/exports
    block: |
      {% for client in nfs_clients %}
      {{ nfs_share_path }} {{ client }}({{ nfs_export_options }})
      {% endfor %}
    create: yes
  notify: Restart NFS

- name: Export NFS directories
  command: exportfs -a

- name: Ensure NFS server is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: true
