---
- name: Setup Database Server (NFS export + PostgreSQL)
  hosts: database_server
  become: true
  roles:
    - nfs_export
    - postgresql

- name: Setup Load Balancer (DNS + HAProxy)
  hosts: load_balancer
  become: true
  roles:
    - bind9
    - haproxy

- name: Setup Nextcloud Server (NFS client + Nextcloud)
  hosts: next_cloud
  become: true
  roles:
    - nfs_client
    - nextcloud

- name: Setup Mail Server (NFS client + Postfix)
  hosts: mail_server
  become: true
  roles:
    - nfs_client
    - postfix

- name: Configure DNS clients
  hosts: all:!load_balancer
  become: true
  roles:
    - dns_client
