- name: Preseed Postfix config
  debconf:
    name: postfix
    question: 'postfix/main_mailer_type'
    value: 'Internet Site'
    vtype: string

- name: Install Postfix
  apt:
    name: postfix
    state: present
    update_cache: true

- name: Ensure Postfix is running
  service:
    name: postfix
    state: started
    enabled: true
