---
- name: Start specified Libvirt VMs
  hosts: localhost
  connection: local
  tasks:
    - name: Parse VMs variable if it's a string
      ansible.builtin.set_fact:
        vm_list: "{{ vms if vms is iterable and vms is not string else vms | from_json }}"
      when: vms is defined

    - name: Ensure VM list is provided and valid
      ansible.builtin.fail:
        msg: "No VMs specified. Use: ansible-playbook start.yml -e 'vms=[\"vm1\",\"vm2\"]'"
      when: vms is not defined or vm_list | length == 0

    - name: Start requested VMs
      community.libvirt.virt:
        name: "{{ item }}"
        state: running
      loop: "{{ vm_list }}"
      register: start_results
      ignore_errors: true

    - name: Report results
      ansible.builtin.debug:
        msg: "VM '{{ item.item }}': {{ 'Started' if item.changed else (item.msg | default('Unknown error')) }}"
      loop: "{{ start_results.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: start_results.results is defined
